In [2]:
import pandas as pd
import numpy as np

In [3]:

#Load in raw excel data
EXP = pd.read_excel(r'MasterNuclei.xlsx', sheet_name = 'Exp') #experimental

ME2 = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'DD-ME2_even-even_nuclei')
MEdelta = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'DD-MEdelta_even-even_nuclei')
PC1 = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'DD-PC1_even-even_nuclei')
NL3S = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'NL3S_even-even_nuclei')


SKMS = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'SKMS_all_nuclei')
SKP = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'SKP_all_nuclei')
SLY4 = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'SLY4_all_nuclei')
SV = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'SV-MIN_all_nuclei')
UNEDF0 = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'UNEDF0_all_nuclei')
UNEDF1 = pd.read_excel (r'MasterNuclei.xlsx', sheet_name = 'UNEDF1_all_nuclei')

SKMS_even = pd.read_excel (r'All_Even-Even_Nuclei.xlsx', sheet_name = 'SKMS_even-even_nuclei')
SKP_even = pd.read_excel (r'All_Even-Even_Nuclei.xlsx', sheet_name = 'SKP_even-even_nuclei')
SLY4_even = pd.read_excel (r'All_Even-Even_Nuclei.xlsx', sheet_name = 'SLY4_even-even_nuclei')
SV_even = pd.read_excel (r'All_Even-Even_Nuclei.xlsx', sheet_name = 'SV-MIN_even-even_nuclei')
UNEDF0_even = pd.read_excel (r'All_Even-Even_Nuclei.xlsx', sheet_name = 'UNEDF0_even-even_nuclei')
UNEDF1_even = pd.read_excel (r'All_Even-Even_Nuclei.xlsx', sheet_name = 'UNEDF1_even-even_nuclei')


#raw = tuple([EXP, ME2, MEdelta, PC1, NL3S, SKMS, SKP, SLY4, SV, UNEDF0, UNEDF1])

In [4]:

def BE(Z,N,W,df):
    try:
        return float(df[(df['Z']==Z) & (df['N']==N) & (df['Wigner']==W)]['BE'])
    except:
        return None

def OneNSE(Z,N,W,df):
    try:
        return BE(Z,N,W,df) - BE(Z,N-1,W,df)
    except:
        return None
    
def OnePSE(Z,N,W,df):
    try:
        return BE(Z,N,W,df) - BE(Z-1,N,W,df)
    except:
        return None

def TwoNSE(Z,N,W,df):
    try:
        return BE(Z,N,W,df) - BE(Z,N-2,W,df)
    except:
        return None

def TwoPSE(Z,N,W,df):
    try:
        return BE(Z,N,W,df) - BE(Z-2,N,W,df)
    except:
        return None

def AlphaSE(Z,N,W,df):
    try:
        return BE(Z,N,W,df) - BE(Z-2,N-2,W,df) - 28.3
    except:
        return None

def TwoPSGap(Z,N,W,df):
    try:
        return TwoPSE(Z,N,W,df) - TwoPSE(Z+2,N,W,df)
    except:
        return None

def TwoNSGap(Z,N,W,df):
    try:
        return TwoNSE(Z,N,W,df) - TwoNSE(Z,N+2,W,df)
    except:
        return None

def DoubleMDiff(Z,N,W,df):
    try:
        return (TwoPSE(Z,N,W,df) - TwoPSE(Z,N-2,W,df))/4
    except:
        return None

def N3PointOED(Z,N,W,df):
    try:
        return (-1)**N*(OneNSE(Z,N,W,df) - OneNSE(Z,N+1,W,df))/2
    except:
        return None

def P3PointOED(Z,N,W,df):
    try:
        return (-1)**Z*(OnePSE(Z,N,W,df) - OnePSE(Z+1,N,W,df))/2
    except:
        return None

def SNESplitting(Z,N,W,df):
    try:
        return (-1)**N*(OneNSE(Z,N,W,df) - OneNSE(Z,N+2,W,df))
    except:
        return None

def SPESplitting(Z,N,W,df):
    try:
        return (-1)**Z*(OnePSE(Z,N,W,df) - OnePSE(Z+2,N,W,df))
    except:
        return None

def WignerEC(Z,N,W,df):
    if Z!=N:
        return None
    try:
        return DoubleMDiff(Z,N,W,df)-(DoubleMDiff(Z-2,N,W,df) + DoubleMDiff(Z,N+2,W,df))/2
    except:
        return None
    
def BEperA(Z,N,W,df):
    try:
        return BE(Z,N,W,df)/(Z+N)
    except:
        return None

In [20]:
def uBE(Z,N,W,df):
    try:
        return float(df[(df['Z']==Z) & (df['N']==N) & (df['Wigner']==W)]['uBE'])
    except:
        return None

def uOneNSE(Z,N,W,df):
    try:
        return uBE(Z,N,W,df) + uBE(Z,N-1,W,df)
    except:
        return None
    
def uOnePSE(Z,N,W,df):
    try:
        return uBE(Z,N,W,df) + uBE(Z-1,N,W,df)
    except:
        return None

def uTwoNSE(Z,N,W,df):
    try:
        return uBE(Z,N,W,df) + uBE(Z,N-2,W,df)
    except:
        return None

def uTwoPSE(Z,N,W,df):
    try:
        return uBE(Z,N,W,df) + uBE(Z-2,N,W,df)
    except:
        return None

def uAlphaSE(Z,N,W,df):
    try:
        return uBE(Z,N,W,df) + uBE(Z-2,N-2,W,df)
    except:
        return None

def uTwoPSGap(Z,N,W,df):
    try:
        return uTwoPSE(Z,N,W,df) + uTwoPSE(Z+2,N,W,df)
    except:
        return None

def uTwoNSGap(Z,N,W,df):
    try:
        return uTwoNSE(Z,N,W,df) + uTwoNSE(Z,N+2,W,df)
    except:
        return None

def uDoubleMDiff(Z,N,W,df):
    try:
        return (uTwoPSE(Z,N,W,df) + uTwoPSE(Z,N-2,W,df))/4
    except:
        return None

def uN3PointOED(Z,N,W,df):
    try:
        return (uOneNSE(Z,N,W,df) + uOneNSE(Z,N+1,W,df))/2
    except:
        return None

def uP3PointOED(Z,N,W,df):
    try:
        return (uOnePSE(Z,N,W,df) + uOnePSE(Z+1,N,W,df))/2
    except:
        return None

def uSNESplitting(Z,N,W,df):
    try:
        return (uOneNSE(Z,N,W,df) + uOneNSE(Z,N+2,W,df))
    except:
        return None

def uSPESplitting(Z,N,W,df):
    try:
        return (uOnePSE(Z,N,W,df) + uOnePSE(Z+2,N,W,df))
    except:
        return None

def uWignerEC(Z,N,W,df):
    if Z!=N:
        return None
    try:
        return uDoubleMDiff(Z,N,W,df)+(uDoubleMDiff(Z-2,N,W,df) + uDoubleMDiff(Z,N+2,W,df))/2
    except:
        return None
    
def uBEperA(Z,N,W,df):
    try:
        return uBE(Z,N,W,df)/(Z+N)
    except:
        return None

In [53]:
def eBE(Z,N,W,df):
    try:
        return float(df[(df['Z']==Z) & (df['N']==N) & (df['Wigner']==W)]['Estimated'])
    except:
        return None

def eOneNSE(Z,N,W,df):
    try:
        return bool(eBE(Z,N,W,df) + eBE(Z,N-1,W,df))
    except:
        return None
    
def eOnePSE(Z,N,W,df):
    try:
        return bool(eBE(Z,N,W,df) + eBE(Z-1,N,W,df))
    except:
        return None

def eTwoNSE(Z,N,W,df):
    try:
        return bool(eBE(Z,N,W,df) + eBE(Z,N-2,W,df))
    except:
        return None

def eTwoPSE(Z,N,W,df):
    try:
        return bool(eBE(Z,N,W,df) + eBE(Z-2,N,W,df))
    except:
        return None

def eAlphaSE(Z,N,W,df):
    try:
        return bool(eBE(Z,N,W,df) + eBE(Z-2,N-2,W,df))
    except:
        return None

def uTwoPSGap(Z,N,W,df):
    try:
        return bool(eTwoPSE(Z,N,W,df) + eTwoPSE(Z+2,N,W,df))
    except:
        return None

def eTwoNSGap(Z,N,W,df):
    try:
        return bool(eTwoNSE(Z,N,W,df) + eTwoNSE(Z,N+2,W,df))
    except:
        return None

def eDoubleMDiff(Z,N,W,df):
    try:
        return bool(eTwoPSE(Z,N,W,df) + eTwoPSE(Z,N-2,W,df))
    except:
        return None

def eN3PointOED(Z,N,W,df):
    try:
        return bool(eOneNSE(Z,N,W,df) + eOneNSE(Z,N+1,W,df))
    except:
        return None

def eP3PointOED(Z,N,W,df):
    try:
        return bool(eOnePSE(Z,N,W,df) + eOnePSE(Z+1,N,W,df))
    except:
        return None

def eSNESplitting(Z,N,W,df):
    try:
        return bool(eOneNSE(Z,N,W,df) + eOneNSE(Z,N+2,W,df))
    except:
        return None

def eSPESplitting(Z,N,W,df):
    try:
        return bool(eOnePSE(Z,N,W,df) + eOnePSE(Z+2,N,W,df))
    except:
        return None

def eWignerEC(Z,N,W,df):
    if Z!=N:
        return None
    try:
        return bool(eDoubleMDiff(Z,N,W,df)+eDoubleMDiff(Z-2,N,W,df)+eDoubleMDiff(Z,N+2,W,df))
    except:
        return None
    
def eBEperA(Z,N,W,df):
    try:
        return eBE(Z,N,W,df)
    except:
        return None

In [6]:
def Wig1(Z, N):
    return (1.8*np.exp(-380*((N-Z)/(N+Z))**2))-(.84*abs(N-Z)*np.exp(-(((N+Z)/26)**2)))

def Wig2(Z, N):
    return -47*(abs(N-Z)/(N+Z))

In [19]:
#Collect all raw exp data into each individual df

covar = [ME2, MEdelta, PC1, NL3S]

skm = [SKMS, SKP, SLY4, SV, UNEDF0, UNEDF1]
skm_even = [SKMS_even, SKP_even, SLY4_even, SV_even, UNEDF0_even, UNEDF1_even]
skm_merged = []
for i in range(len(skm)):
    skm_merged.append(skm[i].combine_first(skm_even[i]))

raw = [EXP]

for c in covar:
    raw.append(c)
for s in skm_merged:
    raw.append(s)

In [20]:
filtered = []
for i, d in enumerate(raw):
    if i == 0:
        df = d.loc[:,['Z', 'N', 'Binding_Energy_(MeV)', 'Estimated', 'Uncertainty']]
    else:
        df = d.loc[:,['Z', 'N', 'Binding_Energy_(MeV)']]
        df['Binding_Energy_(MeV)'] = df['Binding_Energy_(MeV)'] * -1
    filtered.append(df)
filtered[0]

        Z    N  Binding_Energy_(MeV)  Estimated  Uncertainty
0       3    0         -6.801000e+03       True    2001.0000
1       4    1          9.000000e+01       True    2005.0000
2       5    1         -2.802000e+03       True    2004.0000
3       1    6          6.580000e+03       True    1001.0000
4       9    4          5.586100e+04       True     494.0000
...   ...  ...                   ...        ...          ...
3553  107  155          1.916722e+06      False      93.0624
3554  108  158          1.941337e+06      False      27.1054
3555  110  159          1.950292e+06      False      31.3923
3556    0    1          0.000000e+00      False       0.0000
3557    1    0          0.000000e+00      False       0.0000

[3558 rows x 5 columns]

In [21]:
def Identity(Z, N):
    return 0
wigs = [Identity, Wig1, Wig2]
wigner_dfs =[]
for i, df in enumerate(filtered):
    if i == 0:
        new_df = pd.DataFrame(columns=['Z', 'N', 'Wigner', 'BE', 'Estimated', 'uBE'])
        for wig in range(3):
            for rowi in range(len(df.index)):
                newBE = df.loc[rowi, 'Binding_Energy_(MeV)'] - wigs[wig](df.iloc[rowi,0], df.iloc[rowi,1])
                new_df.loc[len(new_df.index)] = [df.loc[rowi,'Z'], df.loc[rowi,'N'], wig, newBE, df.loc[rowi,'Estimated'], df.loc[rowi,'Uncertainty']]
    else:
        new_df = pd.DataFrame(columns=['Z', 'N', 'Wigner', 'BE'])
        for wig in range(3):
            for rowi in range(len(df.index)):
                newBE = df.loc[rowi, 'Binding_Energy_(MeV)'] - wigs[wig](df.iloc[rowi,0], df.iloc[rowi,1])
                new_df.loc[len(new_df.index)] = [df.loc[rowi,'Z'], df.loc[rowi,'N'], wig, newBE]
    wigner_dfs.append(new_df)
wigner_dfs[0]

         Z    N  Wigner            BE  Estimated  Uncertainty
0        3    0       0 -6.801000e+03       True    2001.0000
1        4    1       0  9.000000e+01       True    2005.0000
2        5    1       0 -2.802000e+03       True    2004.0000
3        1    6       0  6.580000e+03       True    1001.0000
4        9    4       0  5.586100e+04       True     494.0000
...    ...  ...     ...           ...        ...          ...
10669  107  155       2  1.916731e+06      False      93.0624
10670  108  158       2  1.941346e+06      False      27.1054
10671  110  159       2  1.950300e+06      False      31.3923
10672    0    1       2  4.700000e+01      False       0.0000
10673    1    0       2  4.700000e+01      False       0.0000

[10674 rows x 6 columns]

In [22]:
mnames = ['EXP', 'ME2', 'MEdelta', 'PC1', 'NL3S', 'SKMS', 'SKP', 'SLY4', 'SV', 'UNEDF0', 'UNEDF1']
qfuncs = [OneNSE, OnePSE, TwoNSE, TwoPSE, AlphaSE, TwoNSGap, TwoPSGap, DoubleMDiff, N3PointOED, P3PointOED, 
          SNESplitting, SPESplitting, WignerEC, BEperA, uOneNSE, uOnePSE, uTwoNSE, uTwoPSE, uAlphaSE, uTwoNSGap, 
          uTwoPSGap, uDoubleMDiff, uN3PointOED, uP3PointOED, uSNESplitting, uSPESplitting, uWignerEC, uBEperA]
qnames = ['OneNSE', 'OnePSE', 'TwoNSE', 'TwoPSE', 'AlphaSE', 'TwoNSGap', 'TwoPSGap', 'DoubleMDiff', 'N3PointOED', 
          'P3PointOED', 'SNESplitting', 'SPESplitting', 'WignerEC', 'BE/A', 'uOneNSE', 'uOnePSE', 'uTwoNSE', 
          'uTwoPSE', 'uAlphaSE', 'uTwoNSGap', 'uTwoPSGap', 'uDoubleMDiff', 'uN3PointOED', 
          'uP3PointOED', 'uSNESplitting', 'uSPESplitting', 'uWignerEC', 'uBE/A']

quan_dfs = []
for m, model in enumerate(wigner_dfs):
    if m == 1:
        qfuncs = qfuncs[:14]
        qnames = qnames[:14]
    print('checkpoint')
    df = pd.DataFrame(columns=qnames)
    for rowi in range(len(model.index)):
        df.loc[len(df.index)] = [q(model.loc[rowi, 'Z'], model.loc[rowi, 'N'], model.loc[rowi, 'Wigner'], model) for q in qfuncs]
    quan_dfs.append(df)
quan_dfs[0]

checkpoint
checkpoint
checkpoint
checkpoint
checkpoint
checkpoint
checkpoint
checkpoint
checkpoint
checkpoint
checkpoint

,OneNSE,OnePSE,TwoNSE,TwoPSE,AlphaSE,TwoNSGap,TwoPSGap,DoubleMDiff,N3PointOED,P3PointOED,...,uAlphaSE,uTwoNSGap,uTwoPSGap,uDoubleMDiff,uN3PointOED,uP3PointOED,uSNESplitting,uSPESplitting,uWignerEC,uBE/A
0,NaN,NaN,NaN,-6801.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,667.0000
1,NaN,-4525.041200,NaN,-7628.041320,NaN,NaN,NaN,NaN,NaN,-816.520600,...,NaN,NaN,NaN,NaN,NaN,3113.06600,NaN,NaN,NaN,401.0000
2,NaN,-2892.000000,NaN,-7417.041200,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,334.0000
3,810.163000,NaN,-101.796000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.0000
4,NaN,-2722.706000,NaN,-3081.425300,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10669,6898.749985,1041.628132,15082.367502,3901.644425,17947.721301,644.148874,NaN,251.997657,506.661891,410.544110,...,184.9104,710.1248,NaN,111.227600,314.46385,233.81485,799.8653,NaN,NaN,0.3552
10670,7832.035620,2597.241903,14566.424932,4105.029611,17921.534521,307.592715,1906.898887,180.405005,702.172639,1021.951811,...,49.2706,351.0924,586.2108,85.538050,39.08340,426.60540,319.0614,1094.1054,NaN,0.1019
10671,6755.865328,1663.514582,15076.009830,2526.305710,16757.731672,75.448050,NaN,204.070967,734.336569,NaN,...,55.3483,329.7846,NaN,80.587075,185.03480,NaN,338.6773,NaN,NaN,0.1167
10672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000
10673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000

In [23]:
final_dfs = [pd.concat([wigner_dfs[i], quan_dfs[i]], axis=1) for i in range(len(wigner_dfs))]

In [24]:
final_dfs[0]

,Z,N,Wigner,BE,Estimated,Uncertainty,OneNSE,OnePSE,TwoNSE,TwoPSE,...,uAlphaSE,uTwoNSGap,uTwoPSGap,uDoubleMDiff,uN3PointOED,uP3PointOED,uSNESplitting,uSPESplitting,uWignerEC,uBE/A
0,3,0,0,-6.801000e+03,True,2001.0000,NaN,NaN,NaN,-6801.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,667.0000
1,4,1,0,9.000000e+01,True,2005.0000,NaN,-4525.041200,NaN,-7628.041320,...,NaN,NaN,NaN,NaN,NaN,3113.06600,NaN,NaN,NaN,401.0000
2,5,1,0,-2.802000e+03,True,2004.0000,NaN,-2892.000000,NaN,-7417.041200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,334.0000
3,1,6,0,6.580000e+03,True,1001.0000,810.163000,NaN,-101.796000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.0000
4,9,4,0,5.586100e+04,True,494.0000,NaN,-2722.706000,NaN,-3081.425300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10669,107,155,2,1.916731e+06,False,93.0624,6898.749985,1041.628132,15082.367502,3901.644425,...,184.9104,710.1248,NaN,111.227600,314.46385,233.81485,799.8653,NaN,NaN,0.3552
10670,108,158,2,1.941346e+06,False,27.1054,7832.035620,2597.241903,14566.424932,4105.029611,...,49.2706,351.0924,586.2108,85.538050,39.08340,426.60540,319.0614,1094.1054,NaN,0.1019
10671,110,159,2,1.950300e+06,False,31.3923,6755.865328,1663.514582,15076.009830,2526.305710,...,55.3483,329.7846,NaN,80.587075,185.03480,NaN,338.6773,NaN,NaN,0.1167
10672,0,1,2,4.700000e+01,False,0.0000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000
10673,1,0,2,4.700000e+01,False,0.0000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000

In [27]:
for i in range(len(final_dfs)):
    final_dfs[i].to_hdf('June2.h5', mnames[i])

OSError: ``./data`` does not exist

# Adding Uncertainities to EXP

In [12]:
qfuncs = [uOneNSE, uOnePSE, uTwoNSE, uTwoPSE, uAlphaSE, uTwoNSGap, uTwoPSGap, uDoubleMDiff, 
          uN3PointOED, uP3PointOED, uSNESplitting, uSPESplitting, uWignerEC, uBEperA]
qnames = ['uOneNSE', 'uOnePSE', 'uTwoNSE', 'uTwoPSE', 'uAlphaSE', 'uTwoNSGap', 'uTwoPSGap', 'uDoubleMDiff', 
          'uN3PointOED', 'uP3PointOED', 'uSNESplitting', 'uSPESplitting', 'uWignerEC', 'uBE/A']
uncer_df = pd.DataFrame(columns=qnames)
model = pd.read_hdf('May23.h5', 'EXP')
sorted = pd.DataFrame(columns=['Uncertainty', 'Estimated'])
unsorted = EXP.loc[:,['Uncertainty', 'Estimated']]
for rowi in range(len(model.index)):
    Z, N, W = model.loc[rowi, 'Z'], model.loc[rowi, 'N'], model.loc[rowi, 'Wigner']
    unsorted_row = unsorted[(unsorted['Z'] == Z) & (unsorted['N'] == N) & (unsorted['Wigner'] == W)]
    sorted.loc[len(sorted.index)] = [unsorted_row.loc['Uncertainty'], unsorted_row.loc[rowi, 'Estimated']]
model = pd.concat([model, sorted], axis=1)
for rowi in range(len(model.index)):
    uncer_df.loc[len(uncer_df.index)] = [q(model.loc[rowi, 'Z'], model.loc[rowi, 'N'], model.loc[rowi, 'Wigner'], model) for q in qfuncs]
final_exp = pd.concat([model, uncer_df], axis=1)

In [16]:
final_exp.loc[:,['Z','N','Estimated','Uncertainty']]

          Z      N Estimated  Uncertainty
0       0.0    1.0      True       2001.0
1       1.0    0.0      True       2005.0
2       1.0    1.0      True       2004.0
3       1.0    2.0      True       1001.0
4       2.0    1.0      True        494.0
...     ...    ...       ...          ...
7645  108.0  157.0       NaN          NaN
7646  108.0  158.0       NaN          NaN
7647  109.0  157.0       NaN          NaN
7648  110.0  159.0       NaN          NaN
7649  110.0  160.0       NaN          NaN

[7650 rows x 4 columns]

In [ ]:
final_exp.to_hdf('May23.h5', 'EXP')

In [22]:
import pandas as pd
x = pd.read_hdf('June2.h5', 'EXP')
for c in x.columns:
    if c not in ['Z', 'N', 'Wigner', 'Estimated']:
        for r in range(len(x.index)):
            x.loc[r,c] = x.loc[r,c]/1000
x

,Z,N,Wigner,BE,Estimated,uBE,OneNSE,OnePSE,TwoNSE,TwoPSE,...,uAlphaSE,uTwoNSGap,uTwoPSGap,uDoubleMDiff,uN3PointOED,uP3PointOED,uSNESplitting,uSPESplitting,uWignerEC,uBE/A
0,3,0,0,-6.801000,True,2.001000,NaN,NaN,NaN,-6.801000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.667000
1,4,1,0,0.090000,True,2.005000,NaN,-4.525041,NaN,-7.628041,...,NaN,NaN,NaN,NaN,NaN,3.113066,NaN,NaN,NaN,0.401000
2,5,1,0,-2.802000,True,2.004000,NaN,-2.892000,NaN,-7.417041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.334000
3,1,6,0,6.580000,True,1.001000,0.810163,NaN,-0.101796,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.143000
4,9,4,0,55.861000,True,0.494000,NaN,-2.722706,NaN,-3.081425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.038000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10669,107,155,2,1916.730683,False,0.093062,6.898750,1.041628,15.082368,3.901644,...,0.184910,0.710125,NaN,0.111228,0.314464,0.233815,0.799865,NaN,NaN,0.000355
10670,108,158,2,1941.346287,False,0.027105,7.832036,2.597242,14.566425,4.105030,...,0.049271,0.351092,0.586211,0.085538,0.039083,0.426605,0.319061,1.094105,NaN,0.000102
10671,110,159,2,1950.300283,False,0.031392,6.755865,1.663515,15.076010,2.526306,...,0.055348,0.329785,NaN,0.080587,0.185035,NaN,0.338677,NaN,NaN,0.000117
10672,0,1,2,0.047000,False,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
10673,1,0,2,0.047000,False,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [23]:
x.to_hdf('June2.h5', 'EXP')

In [49]:
import pandas
J2df = pd.read_hdf('June2.h5', 'EXP')
J2df

,Z,N,Wigner,BE,Estimated,uBE,OneNSE,OnePSE,TwoNSE,TwoPSE,...,uAlphaSE,uTwoNSGap,uTwoPSGap,uDoubleMDiff,uN3PointOED,uP3PointOED,uSNESplitting,uSPESplitting,uWignerEC,uBE/A
0,3,0,0,-6.801000,True,2.001000,NaN,NaN,NaN,-6.801000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.667000
1,4,1,0,0.090000,True,2.005000,NaN,-4.525041,NaN,-7.628041,...,NaN,NaN,NaN,NaN,NaN,3.113066,NaN,NaN,NaN,0.401000
2,5,1,0,-2.802000,True,2.004000,NaN,-2.892000,NaN,-7.417041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.334000
3,1,6,0,6.580000,True,1.001000,0.810163,NaN,-0.101796,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.143000
4,9,4,0,55.861000,True,0.494000,NaN,-2.722706,NaN,-3.081425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.038000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10669,107,155,2,1916.730683,False,0.093062,6.898750,1.041628,15.082368,3.901644,...,0.184910,0.710125,NaN,0.111228,0.314464,0.233815,0.799865,NaN,NaN,0.000355
10670,108,158,2,1941.346287,False,0.027105,7.832036,2.597242,14.566425,4.105030,...,0.049271,0.351092,0.586211,0.085538,0.039083,0.426605,0.319061,1.094105,NaN,0.000102
10671,110,159,2,1950.300283,False,0.031392,6.755865,1.663515,15.076010,2.526306,...,0.055348,0.329785,NaN,0.080587,0.185035,NaN,0.338677,NaN,NaN,0.000117
10672,0,1,2,0.047000,False,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
10673,1,0,2,0.047000,False,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000